# Copyright (C) 2022-2023 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

FROM intel/ai-workflows:odqa-haystack-api

COPY . /home/user/application

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    tesseract-ocr-chi-sim 

RUN apt-get update && apt-get  -y install ffmpeg \
    libsm6 \
    libxext6 

RUN pip install opencv-python==4.6.0.66
RUN pip install paddlepaddle==2.4.2
RUN pip install paddleocr==2.6.1
