# Copyright (C) 2022-2023 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

version: "3.7"
services:
  haystack-api:
    image: "intel/ai-workflows:odqa-haystack-api"
    network_mode: "host"
    volumes:
      - $APPLICATION:/home/user/application
      - $OUTPUT:/home/user/output
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - PIPELINE_YAML_PATH=$PIPELINE_PATH
      - QUERY_PIPELINE_NAME=$PIPELINE_NAME
      - INDEX_NAME=$INDEX_NAME
      - CONCURRENT_REQUEST_PER_WORKER
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    depends_on:
      - postsql-db
    # Starts REST API with only 2 workers so that it can be run on systems with just 4GB of memory
    # If you need to handle large loads of incoming requests and have memory to spare, consider increasing the number of workers
    command: "/bin/bash -c 'sleep 10 && gunicorn rest_api.application:app -b 0.0.0.0 -k uvicorn.workers.UvicornWorker --workers 1 --timeout 600'"

  postsql-db:
    image: "postgres:14.1-alpine"
    
    
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - /$DB:/var/lib/postgresql/data

  ui:
    image: "intel/ai-workflows:odqa-haystack-ui"
    network_mode: host
    ports:
      - 8501:8501
    restart: on-failure
    volumes:
      - $UI_CONFIG_DIR:/home/user/data/
    environment:
      - API_ENDPOINT=http://localhost:8000
      - PIPELINE_PATH=$PIPELINE_PATH
      - DISABLE_FILE_UPLOAD=True
      - DEFAULT_QUESTION_AT_STARTUP
      - DEFAULT_DOCS_FROM_RETRIEVER
      - DEFAULT_NUMBER_OF_ANSWERS
      - http_proxy=
      - https_proxy=
      - no_proxy=$NO_PROXY
    command: "/bin/bash -c 'sleep 15 && python -m streamlit run ui/webapp.py'"
